version: "2.0"
services:
  backend:
    build:
      context: notes-manager
    restart: always
    ports:
      - 8000:8000

  frontend:
    build:
      context: todo-frontend
    ports:
      - 80:80